### ISSUE TITLE
Add the admin role and allow the approval or disapproval of memes

### ISSUE THREAD

**Issue by jdjuan** [jdjuan/pr-memes#3]
- Register our emails as Admins on the Firebase Console
- Add a button for authentication. Prefer Google OAuth (as we won't need another way)
- If an Admin is authenticated, he/she will see a toggle button for approving or disapproving a meme
- Finally, update the Firebase rules for security, find a way to restrict the update of the approval property only to admins (I guess this is done in the Firestore database rules)

**Comment by ni500** [comment]
I would like to do this:
[ ] Login component (Just a Goole Signin // Signout button at this moment) 
[ ] Auth service to authenticate users with rol
[ ] isAdmin guard to access approval view
[ ] Firestore rule: just logged in users can upload a meme
[ ] Firestore rule: just admin rol users can edit memes

If its ok for you guys I can assign this issue to my self 🙂
